# backend/Dockerfile

FROM node:18-alpine

WORKDIR /app

# Copy package files first (for caching)
COPY package*.json ./

RUN npm install

# Copy rest of code
COPY . .

EXPOSE 5000

CMD ["node", "server.js"]
